
package apachecommonsdemo;

import org.apache.commons.lang3.math.NumberUtils;

/**
 *
 * @author skorkmaz
 */
public class NumberUtilsDemo extends javax.swing.JFrame {
    
    private static final int INT_ARRAY[] = {2, -1, 20, 3};

    public NumberUtilsDemo() {
        initComponents();
        String arrayStr = "{";
        for (int i = 0; i < INT_ARRAY.length; i++) {
            if (i == INT_ARRAY.length - 1) {
                arrayStr = arrayStr + INT_ARRAY[i];
            } else {
                arrayStr = arrayStr + INT_ARRAY[i] + ", ";
            }
        }
        jlIntArray.setText(arrayStr + "}");
        jlMin.setText("");
        jlMax.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlIntArray = new javax.swing.JLabel();
        jbGetMin = new javax.swing.JButton();
        jbGetMax = new javax.swing.JButton();
        jlMin = new javax.swing.JLabel();
        jlMax = new javax.swing.JLabel();

        setTitle("NumberUtils Demo");
        setAlwaysOnTop(true);

        jlIntArray.setText("intArray");

        jbGetMin.setText("--> Get Min -->");
        jbGetMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGetMinActionPerformed(evt);
            }
        });

        jbGetMax.setText("--> Get Max -->");
        jbGetMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGetMaxActionPerformed(evt);
            }
        });

        jlMin.setText("jLabel1");

        jlMax.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbGetMax)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlIntArray)
                        .addGap(18, 18, 18)
                        .addComponent(jbGetMin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlMin)
                    .addComponent(jlMax))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGetMin)
                    .addComponent(jlMin))
                .addGap(12, 12, 12)
                .addComponent(jlIntArray)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGetMax)
                    .addComponent(jlMax))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGetMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGetMinActionPerformed
        jlMin.setText(String.valueOf(NumberUtils.min(INT_ARRAY)));
    }//GEN-LAST:event_jbGetMinActionPerformed

    private void jbGetMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGetMaxActionPerformed
        jlMax.setText(String.valueOf(NumberUtils.max(INT_ARRAY)));
    }//GEN-LAST:event_jbGetMaxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumberUtilsDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumberUtilsDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumberUtilsDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberUtilsDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NumberUtilsDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbGetMax;
    private javax.swing.JButton jbGetMin;
    private javax.swing.JLabel jlIntArray;
    private javax.swing.JLabel jlMax;
    private javax.swing.JLabel jlMin;
    // End of variables declaration//GEN-END:variables
}
