package tabbedpaneuidemo;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 * Usage of custom UI.
 *
 * @author skorkmaz
 */
public class NewJFrame extends javax.swing.JFrame {

    public NewJFrame() {
        initComponents();
        jtp.setUI(new MyTabbedPaneUI());

        jtp.add("My Tab 1", new JPanel());
        addLabelAndButtonAt(0);
        jtp.add("My Tab 2", new JPanel());
        addLabelAndButtonAt(1);
    }

    private void addLabelAndButtonAt(int iTab) {
        JLabel jl = new JLabel(jtp.getTitleAt(iTab));
        jl.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 5));

        JPanel jp = new JPanel(new GridBagLayout());
        jp.setOpaque(false);
        JButton jb = new JButton("x");
        jb.setBorder(null);

        GridBagConstraints gbc = new GridBagConstraints();
        jp.add(jl, gbc);
        gbc.ipadx = 10;
        jp.add(jb, gbc);

        jtp.setTabComponentAt(iTab, jp);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtp = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TabbePaneUI Demo - April 2016");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtp, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtp, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        //Note that you should not select a default look and feel (e.g. Nimbus) because then you will not be able to see the effect coded in MyTabbedPaneUI.        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jtp;
    // End of variables declaration//GEN-END:variables
}
