package tableadvanced;

import java.awt.Rectangle;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.NumberFormatter;

/**
 * Value 2X panel.
 *
 * @author skorkmaz
 */
public class Val2XPanel extends javax.swing.JPanel {

    public Val2XPanel(Rectangle rect) {
        initComponents();
        setBounds(rect);
    }

    double getVal2X() {
        double val = Double.NaN;
        try {            
            NumberFormatter nf = (NumberFormatter) jftfVal2X.getFormatter();
            val = ((Number)nf.stringToValue(jftfVal2X.getText())).doubleValue();
        } catch (ParseException ex) {
            Logger.getLogger(Val2XPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return val;
    }

    void setVal2X(double val2X) {
        NumberFormatter nf = (NumberFormatter) jftfVal2X.getFormatter();
        String txt = nf.getFormat().format(val2X);
        jftfVal2X.setText(txt);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jftfVal2X = new javax.swing.JFormattedTextField();

        setLayout(null);

        jftfVal2X.setBackground(new java.awt.Color(0, 255, 255));
        jftfVal2X.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        add(jftfVal2X);
        jftfVal2X.setBounds(0, 2, 100, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jftfVal2X;
    // End of variables declaration//GEN-END:variables

}
